### ISSUE TITLE
"Cancel" button in edit person

### ISSUE THREAD

**Issue by rvkupper** [mhvis/tutti#24]
I'd like to have a cancel button when I accidentally edit a member when I only wanted to view them. 
Preferably in the bar of attached picture. 

![Screenshot from 2020-04-17 17-13-25](https://user-images.githubusercontent.com/55243579/79584590-e6155f00-80ce-11ea-9978-9744566152c5.png)

**Comment by mhvis** [comment]
You can press F5 to do that. I don't think that we need an additional button next to F5/refresh.

**Comment by mhvis** [comment]
Ik sluit deze, als je toch een extra knop wilt ipv F5 moet je hem even heropenen
