### ISSUE TITLE
SEPA

### ISSUE THREAD

**Issue by mhvis** [mhvis/tutti#70]
Penno kreeg error bij Q-rekening/SEPA:

```
Traceback (most recent call last):
  (..)
  File "/app/src/pennotools/views.py", line 51, in post
    dav_persons = read_exc(wb_debit, True, read_exc(wb_credit, False, {}))
  File "/app/src/pennotools/qrekening/wb.py", line 58, in read_exc
    amount = Decimal(row['Openstaand']).quantize(Decimal('1.00'))

Exception Type: InvalidOperation at /penno/qrekening/
Exception Value: [<class 'decimal.ConversionSyntax'>]
```

**Comment by gwvdh** [comment]
Gok dat dit een probleem is met non-numerieke karakters. Als je de data uit davilex eerst in Excel kopieerd wordt het een numerieke value zonder een euro teken. De Q-rekening velden zijn nu opeens tekst velden i.p.v. file fields. Ik weet niet waarom, want in de pennotools forms.py is dit nogsteeds een FileField.
https://github.com/mhvis/tutti/blob/2e0a27cf5cc7816803a26f2b8f7df9433acb96e3/pennotools/forms.py#L56-L64

Ik heb het idee dat er een oude/andere versie nu live is ofzo, want het kenmerkID dat ik met de laatste merge had toegevoegd is ook verdwenen

**Comment by gwvdh** [comment]
Anyway, mss is het alsnog goed om er op te checken en de string te sanitizen. Voor de Decimal conversion nog even een regex zoals:
```
openstaand: str = row['Openstaand]
re.sub(r'[^0-9.,]', '', openstaand)
amount = Decimal(openstaand).quantize(Decimal('1.00'))
```

https://github.com/mhvis/tutti/blob/2e0a27cf5cc7816803a26f2b8f7df9433acb96e3/pennotools/qrekening/wb.py#L55-L58
